version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_PASS}
    depends_on:
      - db
    networks:
      - database

  server:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - internal
    volumes:
      - ../src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../src:/var/www/html:delegated
    networks:
      - internal

networks:
  internal:
    driver: bridge
  database:
    driver: bridge
