version: "3"

services:
  db:
    image: mysql:latest
    container_name: mysql_database
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    networks:
      - database
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - database

  server:
    image: nginx
    container_name: nginx_web_server
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - internal
    volumes:
      - ../src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: php
    restart: always
    volumes:
      - ../src:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - internal

networks:
  internal:
    driver: bridge
  database:
    driver: bridge

volumes:
  mysql-data:
